name: run-tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: |
        if command -v jest &> /dev/null; then
          jest
        else
          echo "Jest not found, running alternative test script..."
        fi
